namespace ModConfigEnhance;

/// <summary>config\ModConfigEnhance\readme.md 的内容，按当前界面语言挑一份（C# 原始字符串；{VERSION} 由 Loc 替换）。
/// 1.0.27 起与项目 README.md 合并为同一份内容：README 为基准，本文件额外保留语言目录细节。</summary>
internal static class LanguageReadme
{
    internal static string For(Loc.UiLang lang) => lang switch
    {
        Loc.UiLang.ZhCn => ZhCn,
        Loc.UiLang.ZhTw => ZhTw,
        _ => En,
    };

    private const string En = """
        # ModConfig Enhance {VERSION}

        PEAK · enhancements for the ModConfig (PEAKLib.ModConfig) settings page · Author AiAe

        *This file is generated by the mod: rewritten on every start and language switch, in the current UI language — manual edits are lost.*

        > Ever find yourself scrolling back and forth through a pile of mod settings just to change one value? Digging through cfg comments to figure out what an option does? Want to add multi-language support to your modpack? From now on, this mod lets you manage your modpack's settings far more elegantly!
        >
        > Tree-style mod list sidebar — √
        > An info panel showing mod name, version, option descriptions and more — √
        > One-click export of all unlocalized texts, free to translate, multi-language supported — √
        > Name sorting and pinning — √
        > Compatible with TimeTheme's purple night theme — √
        > …and other small tweaks

        ## What is in this folder

        | Path | Purpose |
        |---|---|
        | `language\xx-yy.txt` | A language file: this mod's UI terms + every mod's option texts |
        | `language\en-us.txt` `zh-cn.txt` `zh-tw.txt` | Built-in. Created once, never overwritten; delete to reset |
        | `export\` | Where "Export texts" and "Untranslated" write their files |
        | `readme.md` | This note |

        Files starting with `_` never show in the dropdown. Only `.txt` files directly in `language\` are read — subfolders are ignored, so keep backups in a subfolder.

        ## Features

        | Feature | Details |
        |---|---|
        | Tree sidebar | The left column lists mods; the selected mod's sections expand beneath it, options on the right. Pinning supported. |
        | | Search, type filters, a Pin column and an Export column that exports only the ticked mods' texts. |
        | | Rows with no matches auto-hide while filtering; keybind options get their own filter button. |
        | Description panel | A persistent panel at the top right: hover/select an option to see its description, default value, range or choices; |
        | | select a mod/section to see its name, version and summary. Scrollable. |
        | UI localization | All UI text comes from language files; a dropdown on the page switches languages instantly. |
        | Translation tools | Export every text awaiting translation / only the untranslated entries; global original ↔ translation toggle; |
        | | live dictionary reload — add as many languages to your modpack as you like! |
        | Gamepad support | Two-level navigation between the left and right panels: A enters/confirms, B steps back, LB/RB switch mods; |
        | | sliders need A to arm before adjusting; on a keybind, press A then hold the key for 1 second to write it. |
        | Theme | Hand-drawn paper look; follows TimeTheme's day/night palette when installed; plus vanilla-style visuals and animations. |

        ## Demo

        ![Night-TimeTheme](https://github.com/AiAe-156/AiAe-PeakMODs/blob/master/ModConfigEnhance/%E5%A4%9C%E6%99%9A1.png)
        *Night theme (TimeTheme)*

        ![Day](https://github.com/AiAe-156/AiAe-PeakMODs/blob/master/ModConfigEnhance/%E7%99%BD%E5%A4%A91.png)
        *Daytime look*

        ![Demonstration](https://github.com/AiAe-156/AiAe-PeakMODs/blob/master/ModConfigEnhance/%E6%BC%94%E7%A4%BA%E8%A7%86%E9%A2%91main.gif)
        *Demo gif (may take a moment to load)*

        ## Dependencies

        - **Required**: BepInEx 5, PEAKLib.Core, PEAKLib.UI, ModConfig 1.8.1
        - **Optional**: XUnity AutoTranslator (untranslated check / original-text toggle / reload / dictionary mirroring — the related buttons stay greyed out without it), TimeTheme (day/night palette)
        - **Conflicts**: LocalFix < 2.17.0 ships the same patch set, so this mod refuses to attach when it's detected; the patches also skip automatically when the ModSettingsLocalization fork (a ModConfig 1.6.0 variant) is present.

        ## Language files

        Directory: `BepInEx\config\ModConfigEnhance\language\`

        File format is identical to XUnity dictionaries: `key=translation`, `//` comments, `\n` newline, `\=` literal equals, `{0}` `{1}` placeholders kept — **never modify anything left of `=`** (it is the key the dictionary matches character-for-character against on-screen text). The first `MCE_…=…` block is this mod's UI terms (stable IDs — translate the right side only); the `original=translation` lines after it are handed to XUnity AutoTranslator.

        Files starting with `_` stay out of the dropdown; only the top-level `.txt` files are read — keep backups in a subfolder.

        ### File naming: `language-code[-variant][_part].txt`

        The filename itself decides its group and how it's displayed — the two suffixes do different jobs:

        | Pattern | Meaning | Examples |
        |---|---|---|
        | `code.txt` | Base group for the language | `zh-cn.txt`, `en-us.txt` |
        | `code-variant.txt` | **Standalone group of the same language code** — a full, independent translation that may use a completely different style | `zh-cn-old.txt`, `zh-cn-memes.txt` |
        | `group_part.txt` | **Sub-file of a group** — merged into the group named before the `_`, loaded after it in filename order, later entries win | `zh-cn_topup.txt`, `zh-cn-old_fix.txt` |

        - **Language code** = the leading `xx` or `xx-yy` of the filename (`zh-cn-old` → `zh-cn`). It only governs two things: the XUnity mirror folder (`Translation\<code>`) and "Follow game language" matching. Aliases: `zh`=`zh-cn`, `en`=`en-us`.
        - **Dropdown label**: a `// display: <name>` first line shows `name (filename)`; without it, the plain filename is shown. Groups with more than one file get `×count` appended. Examples: `zh-cn-old.txt` (with `// display: Old translation`) → `Old translation (zh-cn-old)`; `zh-cn.txt` (none) → `zh-cn`; `zh-cn-basic.txt` (`// display: 简体中文`) + `zh-cn-basic_ModB.txt` → `简体中文 (zh-cn-basic) ×2`.
        - **Loaded-files list**: after picking a group, the panel lists each file with its own display name, e.g. `zh-cn-basic.txt (简体中文)`, `zh-cn-basic_ModB.txt (Modb)`.
        - **Tooltip emphasis**: in `MCE_TIP_*` hover-tooltips, text inside `` `…` `` or `“…”` renders in the title color (backticks hidden, curly quotes kept).
        - **Variant groups are independent**: same-code groups are equal, self-contained translations — the untranslated check counts only the current group, like `cn` vs `tw`.
        - **Follow game language** with several same-code groups prefers the group named exactly the code (`zh-cn`), else the first variant.

        ### Adding a language

        1. **Export** — mod settings → left column → **Export texts**; tick **Selected only** first to drop the mods you don't need (this mod is always included).
        2. **Translate** — fill the right side of each `=` following the rules inside the file; keep `\n` and `\=` notation as-is.
        3. **Rename & place** — save as UTF-8 and name by the rules above: a new language uses `lowercase-code.txt` (`de-de.txt`, `ja-jp.txt`…), an alternative style for the same language uses `code-variant.txt`; move it into `language\`. To change the dropdown label, write `// display: <name>` on the first line.
        4. **Enable** — back in the game: click **Refresh**, pick the language in the dropdown — it loads automatically. After edits, click **Reload texts**.

        ### Group sub-files & top-ups

        `group_part.txt` merges into the group named before the `_` (base file first, sub-files in filename order — text sorting, not numeric; pad sequential numbers `01`, `02`, `10`):

        ```text
        zh-cn.txt             base file
        zh-cn_01_base.txt     sub-file: appended
        zh-cn_20_topup.txt    sub-file: overrides same keys
        zh-cn-old_fix.txt     joins the zh-cn-old group, not zh-cn
        ```

        - Later files override earlier ones; identical entries are skipped; conflicting translations are logged with their source files.
        - Empty values, original-text placeholders and unchanged English `MCE_` values cannot overwrite existing translations.
        - A group is validated before applying; format errors (missing `=`, empty file…) show in the description panel in orange with line numbers — fix and reload.

        Top-up workflow: keep the old files → **Untranslated** → translate → save as a new `_part` file for the same group → **Reload texts**. The untranslated check counts only the current group's own coverage; **do not replace your full translation with a patch**. For a new language or variant group, click **Refresh** and select it.

        ### After picking a language (no restart)

        - This mod's UI switches at once; the description panel lists every loaded filename in load order (with each file's display name).
        - XUnity AutoTranslator switches to that group's language code: its dictionary folder becomes `Translation\<code>\Text\`, the translations are written there as `ModConfigEnhance_<code>.txt`, dictionaries reload, texts without a translation show the original, and `Language=` in `AutoTranslatorConfig.ini` is updated for the next start. Toggle this link with this mod's **Switch XUnity language with the language file** option.

        ## Toolbar

        | Button | What it does |
        |---|---|
        | Export texts | Exports all UI texts to `export\` (this mod's `MCE_` block + one block per mod, manifest summaries included) |
        | Untranslated | Exports only the entries the XUnity dictionary doesn't cover (requires XUnity AutoTranslator) |
        | Selected only | Adds an "Export" checkbox column to the sidebar — only the ticked mods get exported (this mod is always included) |
        | Show original / Show translated | Global original ↔ translation toggle (same as XUnity's Alt+T) |
        | Reload texts | Re-reads the language files and refreshes XUnity's dictionaries |
        | Open folder | Opens `config\ModConfigEnhance\` |
        | Language ▾ / Refresh | Pick a language group; **Refresh** after adding a new language, **Reload texts** after adding a sub-file to an existing one |

        ## Gamepad controls

        - **Navigation**: stick / D-pad moves focus; A confirms/enters; B steps back level by level (slider → editing → capture → right panel → left panel → leave page)
        - **LB/RB**: switch mods
        - **Sliders**: A arms value mode, left/right adjust, A or B exits; each step is 0.5% of the range — hold for 1s to auto-repeat at 10 steps/s, 3s for 40 steps/s
        - **Dropdowns**: A opens, up/down to move, A picks, B closes
        - **Input fields**: A starts editing, B exits. No on-screen keyboard — type on a physical keyboard or the platform OSK (Steam+X on Steam Deck)
        - **Keybinds**: A starts capture, hold the target key for 1 second to write it; B cancels

        ## Config file

        `BepInEx\config\com.aiae.modconfigenhance.cfg`:

        | Section | Contents |
        |---|---|
        | 1. Layout | Tree sidebar and description panel toggles (restart required) |
        | 2. Localization | UI localization, hide localization buttons (instant), make XUnity follow the chosen language file, disable XUnity machine translation (on by default — turn off to restore machine translation) |
        | 3. State | Runtime state: language file, pins, export exclusions etc. (Hidden) |

        ## Extra details

        - **Sidebar cascade**: reopening the settings page reveals the selected mod row first, then one row above and below per beat; at the bottom rows appear upward; with no valid selection it starts from the top. Closing ends the animation and restores pending rows.
        - **Wheel step**: the left sidebar wheel step is about a third of vanilla, with a ~0.1s ease; scrollbar dragging and controller positioning take over immediately — other scroll areas are unchanged.
        - **Description panel**: selecting a mod/section shows its name, version and manifest summary; hovering/focusing an option restores that option's description.

        ## Feedback & contribute

        `2323086800@qq.com` / QQ group `1104320838` — finished language files are welcome too; send them to AiAe and they ship with the next release.

        """;

    private const string ZhCn = """
        # ModConfig Enhance {VERSION}

        PEAK · ModConfig（PEAKLib.ModConfig）设置页增强 · 作者 AiAe

        *本文件由模组自动生成：每次启动 / 切语言后按当前界面语言重写，手工改动会被覆盖。*

        > 你是否经常在一堆模组配置里反复来回滑动，就为了改某一个参数；是否因为想知道某个配置项是做什么的而去 config 里翻注释；想为整合包添加多语言支持……从现在开始，你可以利用该模组更加优雅地管理你的整合包！
        >
        > 模组列表树形栏 - √
        > 一个能显示模组名称，版本号，配置项注释等信息的说明框 - √
        > 一键导出所有非本地化语言并自由发挥翻译，支持多重语言 - √
        > 名称排序和置顶功能 - √
        > 兼容 TimeTheme 夜间幽紫主题 - √
        > 以及其他小改动……

        ## 这个目录放什么

        | 路径 | 用途 |
        |---|---|
        | `language\xx-yy.txt` | 语言文件：本模组界面词条 + 所有模组的选项文本 |
        | `language\en-us.txt` `zh-cn.txt` `zh-tw.txt` | 内建三种。只建不覆，可随意改；删掉即恢复默认 |
        | `export\` | 「导出翻译」「补漏翻」写文件的地方 |
        | `readme.md` | 本说明 |

        `_` 开头的文件不进下拉框；只读 `language\` 当前层的 `.txt`，子目录被忽略——备份请放进子目录。

        ## 功能

        | 功能 | 说明 |
        |---|---|
        | 树形侧栏 | 左栏显示模组列表，选中模组会在其下方展开分区。可以置顶右侧为选项。 |
        | | 支持搜索、类型筛选、置顶选中列、仅导出勾选列的翻译文本。 |
        | | 筛选时无匹配项的行自动隐藏；单独为按键设置添加了筛选按钮。 |
        | 说明面板 | 右上方常驻面板：悬停/选中选项时显示其说明、默认值、范围或可选值； |
        | | 选中模组/分区时显示该模组名称、版本与简介。可滚动 |
        | 界面本地化 | 全部界面文字走语言文件，页面内下拉实时切换语言 |
        | 翻译工具 | 导出全部待翻文本/导出未翻条目、原文/译文全局切换； |
        | | 支持实时重载词典、为你的整合包添加多重语言！ |
        | 手柄支持 | 左栏↔右栏两级导航，A 进入/确认、B 逐级返回、LB/RB 切模组； |
        | | 滑条按 A 激活后调值；按键绑定按 A 后长按 1 秒写入 |
        | 主题 | 手绘纸面风格；装 TimeTheme 后随昼夜配色；还有适配原本风格的视觉风格和动效 |

        ## 演示

        ![Night-TimeTheme](https://github.com/AiAe-156/AiAe-PeakMODs/blob/master/ModConfigEnhance/%E5%A4%9C%E6%99%9A1.png)
        *夜晚主题(TimeTheme)*

        ![Day](https://github.com/AiAe-156/AiAe-PeakMODs/blob/master/ModConfigEnhance/%E7%99%BD%E5%A4%A91.png)
        *白天样式*

        ![Demonstration](https://github.com/AiAe-156/AiAe-PeakMODs/blob/master/ModConfigEnhance/%E6%BC%94%E7%A4%BA%E8%A7%86%E9%A2%91main.gif)
        *演示图片(可能需要时间加载)*

        ## 依赖

        - **必须**：BepInEx 5、PEAKLib.Core、PEAKLib.UI、ModConfig 1.8.1
        - **可选**：XUnity AutoTranslator（补漏翻/原文切换/重载/词典镜像；未装则对应按钮置灰）、TimeTheme（昼夜配色）
        - **互斥**：LocalFix < 2.17.0 自带同一套补丁，检测到即拒绝挂载；ModSettingsLocalization 分支版在场时自动跳过

        ## 语言文件

        目录：`BepInEx\config\ModConfigEnhance\language\`

        文件格式同 XUnity 词典：`键=译文`，`//` 注释，`\n` 换行、`\=` 等号、`{0}` `{1}` 占位符原样保留——**等号左边一个字符都别动**（它是词典逐字匹配屏幕文字的键，改动就永远对不上）。第一段 `MCE_…=…` 是本模组界面词条（键为稳定 ID，只翻右边），之后的 `原文=译文` 由各模组交给 XUnity 使用。

        `_` 开头的文件不进下拉框；只读当前层的 `.txt`，子目录被忽略——备份请放进子目录。

        ### 文件名规则：`语言码[-变体][_分包].txt`

        文件名自己决定它怎么进组、怎么显示，两种后缀各司其职：

        | 写法 | 含义 | 例子 |
        |---|---|---|
        | `语言码.txt` | 该语言的基础组 | `zh-cn.txt`、`en-us.txt` |
        | `语言码-变体.txt` | **同语言码的独立分组**：与基础组平起平坐，各自一套完整翻译，风格可以完全不同 | `zh-cn-old.txt`、`zh-cn-整活版.txt` |
        | `组名_分包.txt` | **组内分包**：并入前缀所指的组，按文件名排序追加加载、后者覆盖前者 | `zh-cn_补翻.txt`、`zh-cn-old_修正.txt` |

        - **语言码** = 文件名开头的 `xx` 或 `xx-yy`（`zh-cn-old` 的码是 `zh-cn`）。它只管两件事：XUnity 镜像目录（`Translation\<码>`）和「跟随游戏语言」匹配。别名：`zh`=`zh-cn`、`en`=`en-us`。
        - **下拉框显示**：文件首行写了 `// display: 名字` 就显示「名字 (文件名)」，没写就显示文件名本身；组内多于一个文件时末尾带 `×数量`。例：`zh-cn-old.txt`（写了 `// display: 旧版翻译`）→ `旧版翻译 (zh-cn-old)`；`zh-cn.txt`（没写）→ `zh-cn`；`zh-cn-basic.txt`（`// display: 简体中文`）+ `zh-cn-basic_ModB.txt` 一组两个 → `简体中文 (zh-cn-basic) ×2`。
        - **说明框加载列表**：选中一组后按加载顺序列出每个文件和它自己的显示名，如 `zh-cn-basic.txt（简体中文）`、`zh-cn-basic_ModB.txt（Modb）`。
        - **注释强调**：`MCE_TIP_*` 悬停注释里，`` `…` `` 或 `“…”` 包住的文字用标题色强调（反引号本身不显示，弯引号保留）。
        - **变体组互不相关**：同码的各组是平等的独立翻译，补漏翻只统计当前组自己翻没翻过——就像 cn 与 tw 的区别，各算各的。
        - **跟随游戏语言**命中同码多组时，优先选组名恰等于语言码的组（`zh-cn`），没有再取第一个变体组。

        ### 如何添加语言

        1. **导出** — 模组设置 → 左栏「导出翻译」，得到 `export\` 下的待翻文件（先勾「仅导出已选」可去掉不需要的模组，本模组恒包含）。
        2. **翻译** — 按文件内说明规则，把译文填在对应键值 `=` 的右边；原文里的 `\n` `\=` 写法保持不变。
        3. **改名放入** — 以 UTF-8 编码保存 → 按上面的规则命名：新语言用 `小写语言码.txt`（`de-de.txt`、`ja-jp.txt`……），同一语言的另一套风格用 `语言码-变体.txt`，放进 `language\`。想改下拉框里的显示名，首行写 `// display: 名字`。
        4. **启用** — 回游戏点「刷新」，在左侧语言下拉框选中它即自动加载；之后改文件点「重载翻译」生效。

        ### 组内分包与补翻

        `组名_分包.txt` 并入前缀所指的组（基础文件先读，分包按文件名排序后读；文字排序而非数值，连续编号建议补零 `01`、`02`、`10`）：

        ```text
        zh-cn.txt             基础文件
        zh-cn_01_基本.txt      分包：追加
        zh-cn_20_补翻.txt      分包：覆盖同名键
        zh-cn-old_修正.txt     并进 zh-cn-old 组，不是 zh-cn 组
        ```

        - 后读覆盖先读；同键同译文跳过；不同有效译文冲突记日志。
        - 空值、与原文相同的占位内容、未修改的 `MCE_` 英文不会覆盖已有译文。
        - 整组校验通过后才应用；格式错误（缺等号、空文件……）在说明面板用橙色带行号提示，修正后重载。

        补翻流程：保留旧文件 → 「补漏翻」→ 翻译 → 另存为本组的新 `_分包` 文件 → 「重载翻译」。补漏翻只统计当前组自己的覆盖情况；**不要用补翻文件替换原文件**；新增语言或新变体组点「刷新」后选择。

        ### 选中语言后（无需重启）

        - 本模组界面立刻切换；说明面板按实际加载顺序列出全部文件名（带各自显示名）。
        - XUnity 同步切到该组的语言码：词典目录变为 `Translation\<码>\Text\`，词条镜像为其中的 `ModConfigEnhance_<码>.txt`，`AutoTranslatorConfig.ini` 的 `Language=` 同步改写。本模组开关 `Switch XUnity language with the language file` 可关闭此联动。

        ## 工具行

        | 按钮 | 作用 |
        |---|---|
        | 导出翻译 | 全部界面文本导出到 `export\`（本模组 `MCE_` 块 + 各模组分块，含 manifest 简介） |
        | 补漏翻 | 只列 XUnity 词典未命中的条目（需 XUnityAutoTranslate） |
        | 仅导出已选 | 侧栏出现「导出」复选框列，只导出勾选模组（本模组恒包含） |
        | 显示原文/译文 | 全局原文/译文切换（=XUnityAutoTranslate Alt+T） |
        | 重载翻译 | 重读语言文件并刷新 XUnityAutoTranslate 词典 |
        | 打开目录 | 打开 `config\ModConfigEnhance\` |
        | 语言 ▾ / 刷新 | 按语言分组选择；新增语言点刷新，同语言新增分包点重载翻译 |

        ## 手柄操作

        - **导航**：摇杆/十字键移动焦点；A 确认/进入；B 逐级返回（调值→编辑→捕获→右栏→左栏→退页）
        - **LB/RB**：切换模组
        - **滑条**：A 激活调值态，左右调值，再按 A 或 B 退出；步进为区间 0.5%，按住 1s 后 10 步/秒、3s 后 40 步/秒
        - **下拉框**：A 展开，上下选项，A 选定，B 关闭
        - **输入框**：A 进入编辑，B 退出。无屏幕键盘——打字靠实体键盘或平台 OSK（Deck 用 Steam+X）
        - **按键绑定**：A 进入捕获，按住目标键 1 秒写入；B 取消

        ## 配置项

        `BepInEx\config\com.aiae.modconfigenhance.cfg`：

        | 分区 | 内容 |
        |---|---|
        | 1. Layout | 树形侧栏、说明面板开关（重启生效） |
        | 2. Localization | 界面本地化、隐藏本地化相关按钮（即时生效）、XUnityAutoTranslate 跟随切换、禁用 XUnityAutoTranslate 机翻（默认开，关闭恢复机翻） |
        | 3. State | 语言文件、置顶、导出排除等运行状态（Hidden） |

        ## 其他细节

        - **左栏渐入动效**：再次打开配置页时，选中模组行先出现，随后每拍向上、向下各显示一行；选在底部则向上显示，无有效选择则从顶部开始；关闭页面结束动画并恢复尚未出现的行。
        - **滚轮步幅**：左栏滚轮步幅约为原版三分之一，配约 0.1 秒短缓动；拖动滚动条或手柄定位会直接接管，其他滚动区域保持原行为。
        - **说明面板细节**：选中模组/分区时显示其名称、版本与 manifest 简介；悬停/选中具体选项时恢复该选项说明。

        ## 问题反馈 · 投稿

        `2323086800@qq.com` / QQ 群 `1104320838`；翻好的语言文件也欢迎寄给作者 AiAe，下个版本随包附带。

        """;

    private const string ZhTw = """
        # ModConfig Enhance {VERSION}

        PEAK · ModConfig（PEAKLib.ModConfig）設定頁增強 · 作者 AiAe

        *本檔案由模組自動生成：每次啟動 / 切語言後按目前介面語言重寫，手動修改會被覆蓋。*

        > 你是否經常在一堆模組設定裡反覆來回捲動，就為了改某一個參數；是否因為想知道某個設定項是做什麼的而去 config 裡翻註解；想為整合包加入多語言支援……從現在開始，你可以利用該模組更加優雅地管理你的整合包！
        >
        > 模組列表樹形欄 - √
        > 一個能顯示模組名稱、版本號、設定項註解等資訊的說明框 - √
        > 一鍵匯出所有未本地化語言並自由發揮翻譯，支援多重語言 - √
        > 名稱排序與置頂功能 - √
        > 相容 TimeTheme 夜間幽紫主題 - √
        > 以及其他小改動……

        ## 這個目錄放什麼

        | 路徑 | 用途 |
        |---|---|
        | `language\xx-yy.txt` | 語言檔案：本模組介面詞條 + 所有模組的設定文字 |
        | `language\en-us.txt` `zh-cn.txt` `zh-tw.txt` | 內建三種。只建不覆，可隨意改；刪掉即恢復預設 |
        | `export\` | 「導出翻譯」「補漏翻」寫檔案的地方 |
        | `readme.md` | 本說明 |

        `_` 開頭的檔案不進下拉框；只讀 `language\` 目前層級的 `.txt`，子目錄被忽略——備份請放進子目錄。

        ## 功能

        | 功能 | 說明 |
        |---|---|
        | 樹形側欄 | 左欄顯示模組列表，選中模組會在其下方展開分類。可以置頂右側為選項。 |
        | | 支援搜尋、類型篩選、置頂選中列、僅匯出勾選列的翻譯文字。 |
        | | 篩選時無匹配項的行自動隱藏；單獨為按鍵設定加入了篩選按鈕。 |
        | 說明面板 | 右上方常駐面板：懸停/選中選項時顯示其說明、預設值、範圍或可選值； |
        | | 選中模組/分類時顯示該模組名稱、版本與簡介。可捲動 |
        | 介面本地化 | 全部介面文字走語言檔案，頁面內下拉即時切換語言 |
        | 翻譯工具 | 匯出全部待翻文字/匯出未翻條目、原文/譯文全域切換； |
        | | 支援即時重載詞典、為你的整合包加入多重語言！ |
        | 手把支援 | 左欄↔右欄兩級導航，A 進入/確認、B 逐級返回、LB/RB 切模組； |
        | | 滑條按 A 啟用後調值；按鍵綁定按 A 後長按 1 秒寫入 |
        | 主題 | 手繪紙面面風格；裝 TimeTheme 後隨晝夜配色；還有適配原本風格的視覺風格與動效 |

        ## 演示

        ![Night-TimeTheme](https://github.com/AiAe-156/AiAe-PeakMODs/blob/master/ModConfigEnhance/%E5%A4%9C%E6%99%9A1.png)
        *夜晚主題(TimeTheme)*

        ![Day](https://github.com/AiAe-156/AiAe-PeakMODs/blob/master/ModConfigEnhance/%E7%99%BD%E5%A4%A91.png)
        *白天樣式*

        ![Demonstration](https://github.com/AiAe-156/AiAe-PeakMODs/blob/master/ModConfigEnhance/%E6%BC%94%E7%A4%BA%E8%A7%86%E9%A2%91main.gif)
        *演示圖片(可能需要時間載入)*

        ## 依賴

        - **必須**：BepInEx 5、PEAKLib.Core、PEAKLib.UI、ModConfig 1.8.1
        - **可選**：XUnity AutoTranslator（補漏翻/原文切換/重載/詞典鏡像；未裝則對應按鈕置灰）、TimeTheme（晝夜配色）
        - **互斥**：LocalFix < 2.17.0 自帶同一套補丁，檢測到即拒絕掛載；ModSettingsLocalization 分支版在場時自動跳過

        ## 語言檔案

        目錄：`BepInEx\config\ModConfigEnhance\language\`

        檔案格式同 XUnity 詞典：`鍵=譯文`，`//` 註解，`\n` 換行、`\=` 等號、`{0}` `{1}` 佔位符原樣保留——**等號左邊一個字元都別動**（它是詞典逐字比對螢幕文字的鍵，改動就永遠對不上）。第一段 `MCE_…=…` 是本模組介面詞條（鍵為穩定 ID，只翻右邊），之後的 `原文=譯文` 由各模組交給 XUnity 使用。

        `_` 開頭的檔案不進下拉框；只讀當前層的 `.txt`，子目錄被忽略——備份請放進子目錄。

        ### 檔名規則：`語言碼[-變體][_分包].txt`

        檔名自己決定它怎麼進組、怎麼顯示，兩種後綴各司其職：

        | 寫法 | 含義 | 例子 |
        |---|---|---|
        | `語言碼.txt` | 該語言的基礎組 | `zh-cn.txt`、`zh-tw.txt` |
        | `語言碼-變體.txt` | **同語言碼的獨立分組**：與基礎組平起平坐，各自一套完整翻譯，風格可以完全不同 | `zh-tw-old.txt`、`zh-cn-整活版.txt` |
        | `組名_分包.txt` | **組內分包**：併入前綴所指的組，按檔名排序追加載入、後者覆蓋前者 | `zh-tw_補翻.txt`、`zh-cn-old_修正.txt` |

        - **語言碼** = 檔名開頭的 `xx` 或 `xx-yy`（`zh-cn-old` 的碼是 `zh-cn`）。它只管兩件事：XUnity 鏡像目錄（`Translation\<碼>`）和「跟隨遊戲語言」匹配。別名：`zh`=`zh-cn`、`en`=`en-us`。
        - **下拉框顯示**：檔案首行寫了 `// display: 名字` 就顯示「名字 (檔名)」，沒寫就顯示檔名本身；組內多於一個檔案時末尾帶 `×數量`。例：`zh-tw-old.txt`（寫了 `// display: 舊版翻譯`）→ `舊版翻譯 (zh-tw-old)`；`zh-tw.txt`（沒寫）→ `zh-tw`；`zh-tw-basic.txt`（`// display: 繁體中文`）+ `zh-tw-basic_ModB.txt` 一組兩個 → `繁體中文 (zh-tw-basic) ×2`。
        - **說明框載入列表**：選中一組後按載入順序列出每個檔案和它自己的顯示名，如 `zh-tw-basic.txt（繁體中文）`、`zh-tw-basic_ModB.txt（Modb）`。
        - **註釋強調**：`MCE_TIP_*` 懸停註釋裡，`` `…` `` 或 `“…”` 包住的文字用標題色強調（反引號本身不顯示，彎引號保留）。
        - **變體組互不相關**：同碼的各組是平等的獨立翻譯，補漏翻只統計當前組自己翻沒翻過——就像 cn 與 tw 的區別，各算各的。
        - **跟隨遊戲語言**命中同碼多組時，優先選組名恰等於語言碼的組（`zh-tw`），沒有再取第一個變體組。

        ### 如何新增語言

        1. **匯出** — 模組設定 → 左欄「導出翻譯」，得到 `export\` 下的待翻檔案（先勾「僅導出已選」可去掉不需要的模組，本模組恆包含）。
        2. **翻譯** — 按檔案內說明規則，把譯文填在對應鍵值 `=` 的右邊；原文裡的 `\n` `\=` 寫法保持不變。
        3. **改名放入** — 以 UTF-8 編碼儲存 → 按上面的規則命名：新語言用 `小寫語言碼.txt`（`de-de.txt`、`ja-jp.txt`……），同一語言的另一套風格用 `語言碼-變體.txt`，放進 `language\`。想改下拉框裡的顯示名，首行寫 `// display: 名字`。
        4. **啟用** — 回遊戲點「重新整理」，在左側語言下拉框選中它即自動載入；之後改檔案點「重載翻譯」生效。

        ### 組內分包與補翻

        `組名_分包.txt` 併入前綴所指的組（基礎檔案先讀，分包按檔名排序後讀；文字排序而非數值，連續編號建議補零 `01`、`02`、`10`）：

        ```text
        zh-tw.txt             基礎檔案
        zh-tw_01_基本.txt      分包：追加
        zh-tw_20_補翻.txt      分包：覆蓋同名鍵
        zh-tw-old_修正.txt     併進 zh-tw-old 組，不是 zh-tw 組
        ```

        - 後讀覆蓋先讀；同鍵同譯文略過；不同有效譯文衝突記日誌。
        - 空值、與原文相同的佔位內容、未修改的 `MCE_` 英文不會覆蓋已有譯文。
        - 整組驗證通過後才套用；格式錯誤（缺等號、空檔案……）在說明面板用橙色帶行號提示，修正後重載。

        補翻流程：保留舊檔案 → 「補漏翻」→ 翻譯 → 另存為本組的新 `_分包` 檔案 → 「重載翻譯」。補漏翻只統計當前組自己的覆蓋情況；**不要用補翻檔案替換原檔案**；新增語言或新變體組點「重新整理」後選擇。

        ### 選中語言後（無需重啟）

        - 本模組介面立刻切換；說明面板按實際載入順序列出全部檔名（帶各自顯示名）。
        - XUnity 同步切到該組的語言碼：詞典目錄變為 `Translation\<碼>\Text\`，詞條鏡像為其中的 `ModConfigEnhance_<碼>.txt`，`AutoTranslatorConfig.ini` 的 `Language=` 同步改寫。本模組開關 `Switch XUnity language with the language file` 可關閉此連動。

        ## 工具列

        | 按鈕 | 作用 |
        |---|---|
        | 導出翻譯 | 全部介面文字匯出到 `export\`（本模組 `MCE_` 塊 + 各模組分塊，含 manifest 簡介） |
        | 補漏翻 | 只列 XUnity 詞典未命中的條目（需 XUnityAutoTranslate） |
        | 僅導出已選 | 側欄出現「導出」複選框列，只匯出勾選模組（本模組恆包含） |
        | 顯示原文/譯文 | 全域原文/譯文切換（=XUnityAutoTranslate Alt+T） |
        | 重載翻譯 | 重讀語言檔案並重新整理 XUnityAutoTranslate 詞典 |
        | 打開目錄 | 打開 `config\ModConfigEnhance\` |
        | 語言 ▾ / 重新整理 | 按語言分組選擇；新增語言點重新整理，同語言新增分包點重載翻譯 |

        ## 手把操作

        - **導航**：搖桿/十字鍵移動焦點；A 確認/進入；B 逐級返回（調值→編輯→捕獲→右欄→左欄→退頁）
        - **LB/RB**：切換模組
        - **滑條**：A 啟用調值態，左右調值，再按 A 或 B 退出；步進為區間 0.5%，按住 1s 後 10 步/秒、3s 後 40 步/秒
        - **下拉框**：A 展開，上下選項，A 選定，B 關閉
        - **輸入框**：A 進入編輯，B 退出。無螢幕鍵盤——打字靠實體鍵盤或平台 OSK（Deck 用 Steam+X）
        - **按鍵綁定**：A 進入捕獲，按住目標鍵 1 秒寫入；B 取消

        ## 設定項

        `BepInEx\config\com.aiae.modconfigenhance.cfg`：

        | 分區 | 內容 |
        |---|---|
        | 1. Layout | 樹形側欄、說明面板開關（重啟生效） |
        | 2. Localization | 介面本地化、隱藏本地化相關按鈕（即時生效）、XUnityAutoTranslate 跟隨切換、禁用 XUnityAutoTranslate 機翻（預設開，關閉恢復機翻） |
        | 3. State | 語言檔案、置頂、匯出排除等執行狀態（Hidden） |

        ## 其他細節

        - **左欄漸入動效**：再次開啟設定頁時，選中模組列先出現，隨後每拍向上、向下各顯示一列；選在底部則向上顯示，無有效選擇則從頂部開始；關閉頁面結束動畫並恢復尚未出現的列。
        - **滾輪步幅**：左欄滾輪步幅約為原版三分之一，配約 0.1 秒短緩動；拖動捲軸或手把定位會直接接管，其他捲動區域保持原行為。
        - **說明面板細節**：選中模組/分類時顯示其名稱、版本與 manifest 簡介；懸停/選中具體選項時恢復該選項說明。

        ## 問題回報 · 投稿

        `2323086800@qq.com` / QQ 群 `1104320838`；翻好的語言檔案也歡迎寄給作者 AiAe，下個版本隨包附帶。

        """;
}
