#nullable enable
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using HarmonyLib;

namespace ModConfigEnhance;

/// <summary>
/// ModConfig Enhance —— 给 PEAKLib.ModConfig 的模组设置页加：树形侧栏、选项说明面板、界面本地化（语言文件可选）、
/// 翻译导出 / 补漏翻 / XUnity 联动、手柄支持。
/// </summary>
[BepInPlugin(PluginGuid, PluginName, PluginVersion)]
[BepInDependency(ModConfigSupport.Guid, BepInDependency.DependencyFlags.HardDependency)]
[BepInDependency(TimeThemeBridge.Guid, BepInDependency.DependencyFlags.SoftDependency)]
[BepInDependency(XUnityBridge.Guid, BepInDependency.DependencyFlags.SoftDependency)]
public class Plugin : BaseUnityPlugin
{
    public const string PluginGuid = "com.aiae.modconfigenhance";
    public const string PluginName = "ModConfig Enhance";
    public const string PluginVersion = "1.0.2";

    internal static ManualLogSource Log { get; private set; } = null!;

    // cfg 说明原文（Loc.ConfigTerms 用同一份字符串做译文的键）
    internal const string DescTreeSidebar = "A vertical mod list on the left; the selected mod's sections expand beneath it, options on the right. Restart to apply.";
    internal const string DescDescriptionPanel = "A panel at the top right shows the hovered option's description, default value and allowed range or choices. Requires the tree sidebar. Restart to apply.";
    internal const string DescUiLocalization = "Localize ModConfig's own UI (Search, Default, Clear, filters …) and this mod's buttons and notices. Texts come from language files in config\\ModConfigEnhance\\language\\, picked in the language row above the mod list. Restart to apply.";
    internal const string DescHideLocalizationButtons = "Above the mod list, hide the export and XUnity button rows; only the language dropdown + Refresh stay, the list moves up and the Export column hides (ticks remembered). Applies at once.";
    internal const string DescSwitchXUnity = "Picking a language file also switches XUnity AutoTranslator to that language: its dictionary folder becomes Translation\\<code>\\Text\\, the file's non-MCE_ translations are written there as ModConfigEnhance_<code>.txt and dictionaries reload. Untranslated texts show the original. Off = never touch XUnity.";
    internal const string DescTameXUnity = "ON by default. While XUnity AutoTranslator is installed, every startup empties Endpoint / FallbackEndpoint in AutoTranslatorConfig.ini so XUnity stays dictionary-only (its factory default GoogleTranslateV2 machine-translates every UI text), and empties the machine-translation caches (_AutoGeneratedTranslations*.txt in every language folder; a one-time .bak copy is kept). Turn off if you rely on live machine translation.";

    internal static ConfigEntry<bool> EnableTreeLayout = null!;
    internal static ConfigEntry<bool> EnableDescriptionPanel = null!;
    internal static ConfigEntry<bool> EnableLocalization = null!;
    internal static ConfigEntry<bool> HideLocalizationButtons = null!;
    internal static ConfigEntry<bool> SwitchXUnity = null!;
    internal static ConfigEntry<bool> TameXUnity = null!;

    /// <summary>界面维护的记忆（Hidden）：选中的语言文件（空 = 跟随游戏）、置顶、不导出、仅导出已选。</summary>
    internal static ConfigEntry<string> LanguageFile = null!;
    internal static ConfigEntry<string> PinnedMods = null!;
    internal static ConfigEntry<string> ExportExcludedMods = null!;
    internal static ConfigEntry<bool> ExportSelectedOnly = null!;
    internal static ConfigEntry<SidebarSortMode> SidebarSort = null!;

    /// <summary>本模组在 ModConfig 列表里的行名 = 它的 FixNaming(插件名)（1.8.1 ModConfigPlugin.cs）。强制置顶与行名上色按它认行，改名时不用同步。</summary>
    internal static readonly string SelfRowName = FixNaming(PluginName);

    private void Awake()
    {
        Log = Logger;
        BindConfig();
        Loc.EnsureBuiltInFiles();
        NormalizeSelfPin();

        if (TameXUnity.Value && XUnityBridge.TameEndpoint() is { } tamed)
        {
            Log.LogInfo($"[翻译] 已适配 XUnityTranslate：{tamed}；词典翻译不受影响，确需机翻请关闭本模组的「Disable XUnity machine translation」选项。");
        }

        Harmony harmony = new(PluginGuid);
        if (EnableTreeLayout.Value)
        {
            ModConfigTreeLayoutPatch.TryApply(harmony);
        }

        if (EnableLocalization.Value)
        {
            ModConfigLocalizationPatch.TryApply(harmony);
        }

        Log.LogInfo($"[{PluginName} v{PluginVersion}] 已加载。");
        Log.LogInfo($"  树形侧栏: {(EnableTreeLayout.Value ? ModConfigTreeLayoutPatch.State : "关")}" +
            $" / 界面本地化: {(EnableLocalization.Value ? ModConfigLocalizationPatch.State : "关")}" +
            $" / 说明面板: {(EnableDescriptionPanel.Value ? "开" : "关")}" +
            $" / 工具行: {(HideLocalizationButtons.Value ? "仅语言行" : (XUnityBridge.Installed ? "全开（含 XUnity 联动）" : "全开（无 XUnity）"))}" +
            $" / 语言: {(string.IsNullOrEmpty(LanguageFile.Value) ? "跟随游戏" : LanguageFile.Value)}");
    }

    private void BindConfig()
    {
        const string secLayout = "1. Layout";
        EnableTreeLayout = Config.Bind(secLayout, "Tree sidebar", true, DescTreeSidebar);
        EnableDescriptionPanel = Config.Bind(secLayout, "Description panel", true, DescDescriptionPanel);

        const string secLoc = "2. Localization";
        EnableLocalization = Config.Bind(secLoc, "UI localization", true, DescUiLocalization);
        HideLocalizationButtons = Config.Bind(secLoc, "Hide localization buttons", false, DescHideLocalizationButtons);
        SwitchXUnity = Config.Bind(secLoc, "Switch XUnity language with the language file", true, DescSwitchXUnity);
        TameXUnity = Config.Bind(secLoc, "Disable XUnity machine translation", true, DescTameXUnity);

        const string secState = "3. State";
        LanguageFile = Config.Bind(secState, "Language file", "",
            new ConfigDescription("Selected language file name without .txt; empty = follow the game language. Maintained by the UI.", null, "Hidden"));
        PinnedMods = Config.Bind(secState, "Pinned mods", "",
            new ConfigDescription("Mods ticked in the Pin column (ModConfig's display names, | separated). Maintained by the UI.", null, "Hidden"));
        ExportExcludedMods = Config.Bind(secState, "Excluded from export", "",
            new ConfigDescription("Mods unticked in the Export column (ModConfig's display names, | separated). Maintained by the UI.", null, "Hidden"));
        SidebarSort = Config.Bind(secState, "Sort mode", SidebarSortMode.Default,
            new ConfigDescription("Sidebar mod-row sort mode, set by the sort dropdown.", null, "Hidden"));
        ExportSelectedOnly = Config.Bind(secState, "Export selected only", false,
            new ConfigDescription("State of the \"Selected only\" toggle. Maintained by the UI.", null, "Hidden"));
    }

    /// <summary>
    /// 置顶集合里不再需要自身行名——强制最顶是结构行为，不再吃「置顶」列的勾选。
    /// 把曾经写进去的那条清掉，保持 cfg 干净。
    /// </summary>
    private static void NormalizeSelfPin()
    {
        string current = PinnedMods.Value ?? "";
        if (current.Length == 0)
        {
            return;
        }

        List<string> kept = new List<string>();
        bool removed = false;
        foreach (string part in current.Split('|'))
        {
            string name = part.Trim();
            if (name.Length == 0)
            {
                continue;
            }

            if (string.Equals(name, SelfRowName, StringComparison.Ordinal))
            {
                removed = true;
                continue;
            }

            kept.Add(name);
        }

        if (removed)
        {
            PinnedMods.Value = string.Join("|", kept);
            Log.LogInfo($"[{PluginName}] 已从置顶集合移除自身行名（自身行现在固定最顶）。");
        }
    }

    private static string FixNaming(string input)
    {
        input = Regex.Replace(input, "([a-z])([A-Z])", "$1 $2");
        input = Regex.Replace(input, "([A-Z])([A-Z][a-z])", "$1 $2");
        input = Regex.Replace(input, "\\s+", " ");
        input = Regex.Replace(input, "([A-Z]\\.)\\s([A-Z]\\.)", "$1$2");
        return input.Trim();
    }

    /// <summary>侧栏模组行排序方式（排序下拉选；置顶行始终在前不受排序影响，本模组行恒第二）。</summary>
    internal enum SidebarSortMode
    {
        /// <summary>ModConfig 原生顺序（≈插件注册/加载顺序）</summary>
        Default,
        /// <summary>加载顺序倒过来</summary>
        LoadReversed,
        /// <summary>按当前显示名正序（zh 排序规则，中文按拼音、英文按字母）</summary>
        Name,
        /// <summary>按当前显示名倒序</summary>
        NameDesc,
    }
}
